sudo: false
language: haskell
git:
  submodules: false

cabal: "3.2"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:

  # Cabal
  - ghc: 8.4.4
  - ghc: 8.6.5
  - ghc: 8.8.3

install:
  - cabal v2-build bv-sized

